import React from 'react'

const Science = () =>
        <div className="science">
                <div className="container">
                        <div className="science-background">
                        </div>
                        <p>Science has always been the most important component of the activities of the Bryansk State Technical University (hereinafter - BSTU). The formation of BSTU as a regional scientific center occurred with the beginning of the formation of scientific schools. Among the first teachers - reputable scientists of the Ordzhonikidzegrad Engineering Institute (the first name of BSTU) - were prof. Kamaev A.A., prof. Bezyazychny V.F., Kirillov A.I., prof. Pamfilov A.V., prof. Ryzhov E.V. and etc.
Leading scientists of those years, and later their students and followers, made an invaluable contribution not only to the formation and development of science at the institute, but also to the development of industrial enterprises in the Bryansk region and Russia.</p>
                        <p>In subsequent years, the institute began to carry out research work in various areas. Scientific schools “Improving the work and finding ways to increase the efficiency of thermal power plants”, “Engineering Technology”, “Researching new information technologies in the field of innovative production and managing socio-economic systems” were established, scientific interests were expanded in a number of areas of the dynamics and strength scientific school transport vehicles ”, dissertation councils were opened for training specialists of the highest category of various industries. Thanks to the large scientific and technical base of BSTU, for many years it has been not only one of the largest higher educational institutions, but also one of the most significant centers of fundamental and applied science in Bryansk and the Bryansk region.</p>
                        <img className="img-left" src={require('../../../common/images/scientist-2.png')} alt="scientist"></img>
                        <p>A wide range of specialists trained at BSTU predetermines the uniqueness of the scientific interests of its scientists: from mechanical engineering to computer simulation of various systems. The unity in one university of such an extensive circle of highly qualified personnel, as well as a large number of doctors and candidates of sciences, allows us to solve at the present level many problems that are beyond the power of highly specialized teams.
During the years of educational and scientific activity, the BSTU has created a unique material and technical base in a number of scientific and technical areas. To date, a number of functioning educational and research laboratories have been formed, on the basis of which R&D is carried out: laboratories of educational and research institutes and faculties (R&D Tribotekhnika; R&D Computing Mechanics; laboratory Dynamics and Strength of Machines; ASNI laboratory and CAD; laboratory of experimental research methods; laboratory of electroautomatics and information-measuring equipment "; laboratory of robotics; laboratory of hydropneumatic automation; laboratory of applying wear-resistant coatings; laboratory of structural mechanics, construction and road machines); Regional center for new information technologies (laboratory of network telecommunication technologies; laboratory of multimedia technologies and web design; laboratory of information protection; laboratory of virtual microscopic analysis); Innovative center of high technologies in mechanical engineering (3D prototyping laboratory; laboratory of integrated software systems and CALS technologies; laboratory of information retrieval and analysis of information on the Internet).</p>
                        <p>Throughout the entire period of existence, BSTU scientists carried out contract work, work on scientific and scientific-technical programs of relevant ministries and scientific foundations.
Scientific research is carried out by research teams consisting of doctors and candidates of sciences. Moreover, graduate students and students are widely involved in research and development, which ensures the continuity of scientific generations and the progressive development of scientific schools.</p>
                        <img className="img-right" src={require('../../../common/images/engineer.jpg')} alt="engineer"></img>
                        <p>BSTU scientific research is focused on priority areas of development of science and technology and critical technologies of the Russian Federation (Decree of the President of the Russian Federation of July 7, 2011 No. 899).
Educational and scientific centers of the university, departments, research laboratories made it possible to use powerful intellectual potential, material base and library fund to obtain significant scientific results.</p>
                        <p>The oldest scientific schools recognized in Russia and abroad continue to develop at the university; new scientific fields are being formed, dynamically developing and gaining recognition. In recent years, as a result of the development of scientific areas, a number of new research laboratories and centers have been organized: Research Laboratory (hereinafter referred to as the NRL) “Wave deformation and combined hardening in additive and subtractive technologies” (created under the program of the Advanced Research Foundation) ; Research Laboratory "Automation, Telemechanics and Metrology"; Research Laboratory "Materials Engineering and Adaptive Technological Systems"; Research Laboratory "Human Ecology and Data Analysis in the Technosphere"; Forensic Research Laboratory; Engineering center in the field of high-tech engineering "High-tech engineering"; Technology and Innovation Support Center (2nd level) and other research units.</p>
                        <p>The development of fundamental and applied science is a priority of the Bryansk State Technical University. Today, the university’s activities are aimed at creating and developing a comprehensive system of scientific research and training of competent high-level specialists (high-class engineers, bachelors, masters, candidates and doctors of sciences) for key sectors of the economy that ensure sustainable development of mechanical engineering, highly efficient integration of science, education and high-tech business, leading positions of the university in the Russian scientific and educational space.</p>
                </div>
        </div>

export default Science